version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /about.html
    destination: /var/www/html/
  - source: /blog.html
    destination: /var/www/html/
  - source: /contact.html
    destination: /var/www/html/
  - source: /proj1.html
    destination: /var/www/html/
  - source: /projects.html
    destination: /var/www/html/
  - source: /singlepost.html
    destination: /var/www/html/
  - source: /fonts/*
    destination: /var/www/html/fonts/
  - source: /images/*
    destination: /var/www/html/images/
  - source: /js/*
    destination: /var/www/html/js/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
